// Code generated by mockery v2.53.4. DO NOT EDIT.

package tasktemplatemocks

import (
	context "context"

	domaintasktemplate "example.com/taskservice/internal/domain/tasktemplate"
	mock "github.com/stretchr/testify/mock"

	task "example.com/taskservice/internal/domain/task"

	tasktemplate "example.com/taskservice/internal/usecase/tasktemplate"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// BatchCreateTasks provides a mock function with given fields: ctx, tasks
func (_m *Repository) BatchCreateTasks(ctx context.Context, tasks []task.Task) (int64, error) {
	ret := _m.Called(ctx, tasks)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreateTasks")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []task.Task) (int64, error)); ok {
		return rf(ctx, tasks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []task.Task) int64); ok {
		r0 = rf(ctx, tasks)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []task.Task) error); ok {
		r1 = rf(ctx, tasks)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *Repository) CreateWithTasks(ctx context.Context, t *domaintasktemplate.Template, tasks []task.Task) (*domaintasktemplate.Template, int64, error) {
	ret := _m.Called(ctx, t, tasks)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTasks")
	}

	var r0 *domaintasktemplate.Template
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domaintasktemplate.Template, []task.Task) (*domaintasktemplate.Template, int64, error)); ok {
		return rf(ctx, t, tasks)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domaintasktemplate.Template, []task.Task) *domaintasktemplate.Template); ok {
		r0 = rf(ctx, t, tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domaintasktemplate.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domaintasktemplate.Template, []task.Task) int64); ok {
		r1 = rf(ctx, t, tasks)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domaintasktemplate.Template, []task.Task) error); ok {
		r2 = rf(ctx, t, tasks)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int64) (*domaintasktemplate.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domaintasktemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domaintasktemplate.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domaintasktemplate.Template); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domaintasktemplate.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *Repository) List(ctx context.Context, filter tasktemplate.ListFilter) ([]domaintasktemplate.Template, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domaintasktemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tasktemplate.ListFilter) ([]domaintasktemplate.Template, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tasktemplate.ListFilter) []domaintasktemplate.Template); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domaintasktemplate.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tasktemplate.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, t
func (_m *Repository) Update(ctx context.Context, t *domaintasktemplate.Template) (*domaintasktemplate.Template, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domaintasktemplate.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domaintasktemplate.Template) (*domaintasktemplate.Template, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domaintasktemplate.Template) *domaintasktemplate.Template); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domaintasktemplate.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domaintasktemplate.Template) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
